### ISSUE TITLE
Example usage inside axios interceptor?

### ISSUE THREAD

**Issue by notflip** [smastrom/notivue#1]
I'm probably wrong about this, can you use the usePush() method outside of a vue component? I suppose not but I'm still wondering.

I was trying to have an error pop up when an axios 403 is encountered.

```
axios.interceptors.response.use(
    (response) => {
        return response;
    },
    async (error) => {
        if (error.response && error.response.status === 403) {
            push.success('Errored')
        }
        return Promise.reject(error);
    }
);
```

But I get a `caught TypeError: Cannot read properties of undefined (reading 'push')`

**Comment by smastrom** [comment]
Hi @notflip, thank you for pointing this out. 

That's because Notivue's store lives **inside** the Vue app (you install it with: `app.use(notivue)`).

When you configure axios as above, (e.g. in a _axios.js_ file that you import in your _.vue_ files), your axios instance will end up living **outside** the Vue app. There's no way you can [inject](https://vuejs.org/guide/components/provide-inject.html#app-level-provide) Vue resources outside of the _setup_ function of a component of a Vue app. This could potentially be also any composable from any other Vue 3 library.

To inject and use Vue resources in your axios instance, the instance must be configured (and live) in the _setup_ function of a Vue component. In such case in App.vue since you expect it to be available everywhere.

I've created a working example with [StackBlitz](https://stackblitz.com/edit/vitejs-vite-srmjzd?file=src%2FApp.vue,src%2FChild.vue,src%2Fmain.js,src%2FuseAxios.js&terminal=dev) but that's how you would do it:

1. Create a `useAxios.js` to setup, provide and inject your instance:

```js
import { provide, inject } from 'vue'
import axios from 'axios'
import { usePush } from 'notivue'

const instanceSymbol = Symbol('')

export function useInstance() {
  return inject(instanceSymbol)
}

export function setupInstance() {
  const push = usePush()

  const instance = axios.create({
    baseURL: 'https://jsonplaceholder.typicode.com'
  })

  instance.interceptors.response.use(
    (response) => {
      push.success('Successfully loaded stuff!')
      return response
    },
    (error) => {
      push.error('There was an error loading your stuff!')
      return Promise.reject(error)
    }
  )

  provide(instanceSymbol, instance)
}
```

2. Call `setupInstance()` in the _setup_ function of your top-level component:

```vue
<!-- App.vue -->

<script setup>
import { Notivue, notifications } from 'notivue'
import { setupInstance } from './useAxios'
import Child from './Child.vue'

setupInstance()
</script>

<template>
  <Child />
  <Notivue :use="notifications" />
</template>
```

3. From now, you'll be able to inject your instance in any children using `useInstance()` (equivalent of `import instance from './axios.js'`):

```vue
<!-- Child.vue -->

<script setup>
import { ref, onMounted } from 'vue'
import { useInstance } from './useAxios'

const instance = useInstance()
const posts = ref()

onMounted(async () => (posts.value = (await instance.get('/posts')).data))
</script>

<template>
  <div v-if="posts">
    <li v-for="post in posts" :key="post.id">{{ post.title }}</li>
  </div>
</template>
```

I'm going to add an example to the documentation, thank you again for pointing this out.

**Comment by notflip** [comment]
@smastrom Thanks for taking the time to explain this! I'm going to try and use Pinia, so that I can import the store inside the file where axios is defined, and have the app wait for a notification to be called. Thanks for this plugin! Love it.
