### ISSUE TITLE
Are you thinking of building a Soner style structure?

### ISSUE THREAD

**Issue by 0fatihyildiz** [smastrom/notivue#43]
example: https://github.com/xiaoluoboding/vue-sonner

**Comment by smastrom** [comment]
Hi @0fatihyildiz, Notivue will never ship a Sonner-like repositioning experience.
The reason behind that is very simple: I developed this package according to my needs and my beliefs.
I'm not sure the macOS-way to group and clear notifications can be the new default for web apps' generic toasts.

However, the package you linked seems a good solution and I suggest to use it instead of Notivue.
