### ISSUE TITLE
Unstable notification visibility with Astro

### ISSUE THREAD

**Issue by MellKam** [smastrom/notivue#62]
Hi! I discovered this when upgraded to `2.4.4` from `2.2.1`. In my astro app,  the notifications are not showing up completely, even though custom events are sent. To test this in another environment, I chose this [example with astro](https://stackblitz.com/edit/withastro-astro-qyesvk). For some reason, the notifications stop appearing after some attempts to reload the page, but events seemed to be received, just as in my case. To be 100% sure that it's not a stackblitz issue, I tried doing it locally and yeah, the problem remained the same. 

https://github.com/smastrom/notivue/assets/51422045/cb574982-76fb-46c6-a70a-69f7d0d09460

**Comment by smastrom** [comment]
I am aware of that, unfortunately either Astro or Vue for Astro changed something regarding their server rendering behavior between those versions that made it unstable. I also had issues with this setup.
Since they both have been releasing only minor versions, it's 100% their "fault", not sure if Astro or Vue though. If it is not fixed on its own in 2 months I'll remove support for Astro because it's not acceptable that Vue packages stop working between minor versions.

**Comment by smastrom** [comment]
Hi @MellKam, I have some updates regarding the matter.

After spending an hour testing combinations of all minor and patch releases of `astro`, `@astrojs/vue`, and `vue` released since their latest major, I was able to identify which package breaks Notivue.

`@astrojs/vue@4.0.8` is the release that if updated to, Notivue will stop working with both MPA and View Transitions. So as a workaround you can pin it to `4.0.7` and expect it to work.

Other packages involved (`astro` and `vue`) instead, can be safely updated to their latest version.

All of the above can be played with on [StackBlitz](https://stackblitz.com/edit/withastro-astro-ze39qs). This is just a clone of the [Astro example](https://stackblitz.com/edit/withastro-astro-qyesvk) where only the `@astrojs/vue` version differs.

According to the above package changelog these were the fixes introduced:

> ## 4.0.8
> 
> ### Patch Changes
> 
> - #9620 - Fixes `class` property hydration error
> 
> - #9490 - Fixes a bug that caused styles referenced by `appEntrypoint` to be excluded from the build

That said, I have no idea why and how this clashes with Notivue as my Astro knowledge is limited to its consumer APIs.

For this reason, I am not sure on how to create a proper useful issue that may lead to solve the bug neither I would expect them to deal with Notivue's codebase as they probably have better things to do.

I would keep investigating in the next days, hoping to get enough material to open an useful issue.

**Comment by MellKam** [comment]
@smastrom Thanks for your investigation. That's really interesting, how the patch release can break whole library XDD

**Comment by smastrom** [comment]
@MellKam I believe it's inevitable as it's not an easy job to coordinate and maintain all these adapters, renderers, and all the core framework issues. At the end of the day they do an incredible job, I wouldn't even know where to start if I was in their shoes honestly.

I'll do my best to investigate even further hoping this can be sorted out as I'd prefer to not drop support for Astro.

And also, please let me know if you still encounter issues with `@astrojs/vue@4.0.7`.

**Comment by MellKam** [comment]
@smastrom I tried to changed the version of `@astrojs/vue` to 4.0.7 in stackblitz, but it still works 50/50

**Comment by smastrom** [comment]
Have you tried with this one: https://stackblitz.com/edit/withastro-astro-qyesvk ?

**Comment by MellKam** [comment]
> Have you tried with this one: https://stackblitz.com/edit/withastro-astro-qyesvk ?

No, but that doesn't work for me either

**Comment by smastrom** [comment]
Well, `v4.0.7` defintely works on Firefox but yeah, on Chrome it doesn't. I also tried to downgrade Notivue till `v2.2.1` but the strange behavior persists. I will take a better look at it and let you know. Thanks for trying it out.
