### ISSUE TITLE
HTML elements in `message` to allow for links with <a></a> and Bootstrap icons

### ISSUE THREAD

**Issue by MartenBE** [smastrom/notivue#66]
I was wondering if it is possible to allow for HTML tags inside the `message` field so we could for example do the following:

```javascript
push.info({
    title: "It's your turn.",
    message: `Don't know how to play? <a href="/rules" target="_blank">You can find the <i class="bi bi-book"></i> rules here.</a>`,
});
```

**Comment by smastrom** [comment]
The built-in `<Notification />` component is not designed with this feature in mind nor it will be. That said, the value of `message` should always be plain text:

- No HTML tags should be contained in `message` otherwise they'll be announced by screen readers.
- The built-in `<Notification />` component by design has limits, for more specific use cases, [Custom Components](https://docs.notivue.smastrom.io/headless/getting-started.html) should be used instead.

With a Custom Component, you are able to create the "perfect notification" according to your use case:

```ts
push.success({
   message: 'You have a new friend request from Maria', // This will be announced
   props: {
      htmlContent: 'You have a new friend request from <a href="/">Maria</a>. Click <a href="/">here</a> to accept.'
   }
})
```

```vue
<div class="sr-only" role="item.ariaRole" aria-live="item.ariaLive">{{ item.message }}</div> <!-- This is invisible and will be announced -->
<div v-html="item.props.htmlContent" /> <!-- This will be displayed -->
```

If you don't want to create a component and write styles, you can always fork the `<Notification />` component and update it according to your needs.
